ARG  JRE_IMAGE=amazoncorretto:8-alpine-jre

FROM ${JRE_IMAGE}
RUN mkdir -p /fitnesse/wiki/fixtures/nl/hsac/fitnesse

WORKDIR /fitnesse

RUN mkdir -p target
VOLUME /fitnesse/target

RUN mkdir -p wiki/FitNesseRoot
VOLUME /fitnesse/wiki/FitNesseRoot

COPY runTests.sh .
COPY rerunFailedTests.sh .
COPY htmlReportIndexGenerator.sh .

ENTRYPOINT ["/fitnesse/runTests.sh"]
CMD []

COPY wiki wiki/
