if: type = pull_request

language: java
jdk:
  - openjdk8

addons:
  chrome: stable

dist: xenial
sudo: required

cache:
  directories:
  - $HOME/.m2

script:
  - mvn -DfitnesseSuiteToRun=HsacAcceptanceTests -DseleniumBrowser=chrome "-DseleniumJsonProfile={'args':['headless', 'disable-gpu']}" test failsafe:integration-test
