ARG  GRAALVM_IMAGE=ghcr.io/graalvm/native-image:latest
ARG  BUSYBOX_IMAGE=busybox:latest

FROM ${GRAALVM_IMAGE} as graal
RUN mkdir -p /fitnesse/target

WORKDIR /fitnesse

COPY target/. target
RUN native-image -jar target/hsac-html-report-generator.jar --static

FROM ${BUSYBOX_IMAGE}
WORKDIR /fitnesse
VOLUME /fitnesse/target

ENTRYPOINT ["/fitnesse/hsac-html-report-generator"]
CMD []

COPY --from=graal /fitnesse/hsac-html-report-generator .
